### PR TITLE
fix list all issues/pulls example

### PR DESCRIPTION
**Pull request by Veeupup**
the latest docs of how to get all pages data has a bug, it is that it won't update the next page next URL after fetching a new page, this pr fix it.

### CODE REVIEW

**Comment by XAMPPRocky** [comment]
Thank you for your PR! Would you actually mind changing this example to use `Octocrab::all_pages` instead? It essentially does this loop for you.

**Comment by Veeupup** [comment]
@XAMPPRocky resolved

**Comment by Veeupup** [comment]
many thanks for your crate `octocrab`, I use it in [databend](https://github.com/datafuselabs/databend) to develop an interesting feature https://github.com/datafuselabs/databend/issues/2975, it simplifies my development.

**Comment by XAMPPRocky** [comment]
Thank you for your PR, and congrats on your first contribution! 🎉

**Pull request merged**
