### PR TITLE
fix: crate build issues with `stream` feature

### PR DESCRIPTION
**Pull request by benpueschel**
Fix a build issue introduced by #690 when building octocrab with the `stream` feature, which the pr checks didn't catch. 

Closes: #707

### CODE REVIEW

**Comment by XAMPPRocky** [comment]
Thank you for your PR! Would you mind adding a step in CI to check the stream feature?

**Comment by benpueschel** [comment]
>   = note: /usr/bin/ld: final link failed: No space left on device
>           collect2: error: ld returned 1 exit status

Are the logs taking up too much space? Could that be the reason ld panics?

**Comment by benpueschel** [comment]
This PR might genuinely be cursed...

**Comment by benpueschel** [comment]
Okay, so there are two more solutions to this problem I can think of.

1. We could add an entire new job which is entirely responsible for checking the stream feature, meaning we (hopefully) don't pollute each runner with two different versions of every single target (one with the default, one with the stream features)
2. run `cargo clean` after successfully building the default feature-set. I really don't like this approach because it'd dramatically increase workflow run time.

Both of these approaches are compromises, and it'd be great if we could somehow universally extract more space - or tell cargo to delete any targets we don't need, without clearing the entire build cache, but that seems to be harder than anticipated. 

Does anyone have a better idea?

**Comment by benpueschel** [comment]
Okay, so there are two more solutions to this problem I can think of.

1. We could add an entire new job which is entirely responsible for checking the stream feature, meaning we (hopefully) don't pollute each runner with two different versions of every single target (one with the default, one with the stream features)
2. run `cargo clean` after successfully building the default feature-set. I really don't like this approach because it'd dramatically increase workflow run time.

Both of these approaches are compromises, and it'd be great if we could somehow universally extract more space on every OS - or tell cargo to delete any targets we don't need, without clearing the entire build cache, but that seems to be harder than anticipated. 

Does anyone have a better idea?

**Comment by Caellian** [comment]
Something like:
```yaml
jobs:
  build:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        channel: [stable, beta, nightly]
        os: [ubuntu, macos, windows]
        features:
          - ""
          - "-F stream"
    steps:
    - uses: actions/checkout@v2
    - run: rustup default ${{ matrix.channel }}
    - run: cargo build --verbose --all-targets ${{ matrix.features }}
    - run: cargo test ${{ matrix.features }}
```

should work&trade;?

**Comment by benpueschel** [comment]
That would definitely queue-up some jobs (GitHub only allows for 20 total concurrent jobs, a maximum of 5 of which can be MacOS runners: https://docs.github.com/en/actions/administering-github-actions/usage-limits-billing-and-administration#usage-limits), but I think that's the most simple solution.

I'll try it out when I have the time to.

**Comment by benpueschel** [comment]
Looks like we're finally passing all tests :)

**Pull request merged**
