### PR TITLE
Implement getting users and reopos by their respective IDs

### LINKED ISSUE #683: Add the ability to get repository ID and use repositories by ID
I haven't dug the GitHub API docs enough, but it seems there is such a thing: https://stackoverflow.com/questions/13902593/how-does-one-find-out-ones-own-repo-id

Getting repo id: https://stackoverflow.com/a/77904644

Accessing by repo ID: https://stackoverflow.com/a/74290453

As a user on StackOverflow said, it's undocumented, but GitHub support said it is supported.

**Rationale for this feature:**
1. Symmetry: issue_number/issue, id/comment, etc. But repo is accessed by 2 strings
2. No need to pass and handle bluky strings in users code. Just a slim number. (Besides you even require a `String`, not any other more generic type)
3. It would be easier to write a wrapper around several Git Hosts, as one my use ids extensively, but this GitHub prefers strings of `owner/repo`..

### PR DESCRIPTION
**Pull request by InAnYan**
Closes #683.

Well, what I basically did is that I introduced `UserRef` and `RepoRef`.

They are enums with two variants: either full form (nickname, owner/name pair), or ids.

I implemented `std::fmt::Display` for them, so that it's easier to operate in API URLs.

No breaking changes!!

### CODE REVIEW

**Comment by InAnYan** [comment]
This is my first PR in Rust, so, uh. It may be not ideal. But I'm ready to improve it

**Comment by InAnYan** [comment]
**CRUCIAL UPDATE**: in order to get repository by id, you need to use `repositories` in the URL, not `repos`.

I'll update this later

**Comment by InAnYan** [comment]
Another update:

To get user by name, `/users/{login}` should be used.

To get user by id, `/user/{id}` should be used.

**Comment by XAMPPRocky** [comment]
Seems like there's some breakage in tests 🙂

**Comment by InAnYan** [comment]
Hi @XAMPPRocky, I'm sorry, but I can't find the source of problem.

The output of `cargo test` is:

```
running 1 test
test should_return_page_with_users ... FAILED

failures:

---- should_return_page_with_users stdout ----
thread 'should_return_page_with_users' panicked at tests/follow_redirect.rs:66:5:
expected successful result, got error: Err(
    GitHub {
        source: GitHubError {
            documentation_url: Some(
                "",
            ),
            errors: None,
            message: "GET on /repo/new-owner/repo/stargazers was not received",
            status_code: 500,
        },
        backtrace: Backtrace [
            { fn: "snafu::backtrace_impl::<impl snafu::GenerateImplicitData for std::backtrace::Backtrace>::generate", file: "/home/ruslan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/snafu-0.8.4/src/backtrace_impl_std.rs", line: 5 },
            { fn: "octocrab::map_github_error::{{closure}}", file: "./src/lib.rs", line: 332 },
            { fn: "octocrab::Octocrab::get_with_headers::{{closure}}", file: "./src/lib.rs", line: 1357 },
            { fn: "octocrab::api::repos::stargazers::ListStarGazersBuilder::send::{{closure}}", file: "./src/api/repos/stargazers.rs", line: 44 },
            { fn: "follow_redirect::should_return_page_with_users::{{closure}}", file: "./tests/follow_redirect.rs", line: 65 },
            { fn: "<core::pin::Pin<P> as core::future::future::Future>::poll", file: "/rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/future/future.rs", line: 123 },
            { fn: "<core::pin::Pin<P> as core::future::future::Future>::poll", file: "/rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/future/future.rs", line: 123 },
            { fn: "tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}::{{closure}}::{{closure}}", file: "/home/ruslan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/scheduler/current_thread/mod.rs", line: 696 },
            { fn: "tokio::runtime::coop::with_budget", file: "/home/ruslan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/coop.rs", line: 107 },
            { fn: "tokio::runtime::coop::budget", file: "/home/ruslan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/coop.rs", line: 73 },
            { fn: "tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}::{{closure}}", file: "/home/ruslan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/scheduler/current_thread/mod.rs", line: 696 },
            { fn: "tokio::runtime::scheduler::current_thread::Context::enter", file: "/home/ruslan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/scheduler/current_thread/mod.rs", line: 423 },
            { fn: "tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}", file: "/home/ruslan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/scheduler/current_thread/mod.rs", line: 695 },
            { fn: "tokio::runtime::scheduler::current_thread::CoreGuard::enter::{{closure}}", file: "/home/ruslan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/scheduler/current_thread/mod.rs", line: 774 },
            { fn: "tokio::runtime::context::scoped::Scoped<T>::set", file: "/home/ruslan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/context/scoped.rs", line: 40 },
            { fn: "tokio::runtime::context::set_scheduler::{{closure}}", file: "/home/ruslan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/context.rs", line: 180 },
            { fn: "std::thread::local::LocalKey<T>::try_with", file: "/rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/thread/local.rs", line: 283 },
            { fn: "std::thread::local::LocalKey<T>::with", file: "/rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/thread/local.rs", line: 260 },
            { fn: "tokio::runtime::context::set_scheduler", file: "/home/ruslan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/context.rs", line: 180 },
            { fn: "tokio::runtime::scheduler::current_thread::CoreGuard::enter", file: "/home/ruslan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/scheduler/current_thread/mod.rs", line: 774 },
            { fn: "tokio::runtime::scheduler::current_thread::CoreGuard::block_on", file: "/home/ruslan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/scheduler/current_thread/mod.rs", line: 683 },
            { fn: "tokio::runtime::scheduler::current_thread::CurrentThread::block_on::{{closure}}", file: "/home/ruslan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/scheduler/current_thread/mod.rs", line: 191 },
            { fn: "tokio::runtime::context::runtime::enter_runtime", file: "/home/ruslan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/context/runtime.rs", line: 65 },
            { fn: "tokio::runtime::scheduler::current_thread::CurrentThread::block_on", file: "/home/ruslan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/scheduler/current_thread/mod.rs", line: 179 },
            { fn: "tokio::runtime::runtime::Runtime::block_on_inner", file: "/home/ruslan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/runtime.rs", line: 361 },
            { fn: "tokio::runtime::runtime::Runtime::block_on", file: "/home/ruslan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/runtime.rs", line: 335 },
            { fn: "follow_redirect::should_return_page_with_users", file: "./tests/follow_redirect.rs", line: 72 },
            { fn: "follow_redirect::should_return_page_with_users::{{closure}}", file: "./tests/follow_redirect.rs", line: 56 },
            { fn: "core::ops::function::FnOnce::call_once", file: "/rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/ops/function.rs", line: 250 },
            { fn: "core::ops::function::FnOnce::call_once", file: "/rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/ops/function.rs", line: 250 },
            { fn: "test::__rust_begin_short_backtrace", file: "/rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/test/src/lib.rs", line: 624 },
            { fn: "test::run_test_in_process::{{closure}}", file: "/rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/test/src/lib.rs", line: 647 },
            { fn: "<core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once", file: "/rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panic/unwind_safe.rs", line: 272 },
            { fn: "std::panicking::try::do_call", file: "/rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs", line: 557 },
            { fn: "std::panicking::try", file: "/rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs", line: 521 },
            { fn: "std::panic::catch_unwind", file: "/rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panic.rs", line: 350 },
            { fn: "test::run_test_in_process", file: "/rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/test/src/lib.rs", line: 647 },
            { fn: "test::run_test::{{closure}}", file: "/rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/test/src/lib.rs", line: 568 },
            { fn: "test::run_test::{{closure}}", file: "/rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/test/src/lib.rs", line: 598 },
            { fn: "std::sys::backtrace::__rust_begin_short_backtrace", file: "/rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/sys/backtrace.rs", line: 152 },
            { fn: "std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}", file: "/rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/thread/mod.rs", line: 538 },
            { fn: "<core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once", file: "/rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panic/unwind_safe.rs", line: 272 },
            { fn: "std::panicking::try::do_call", file: "/rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs", line: 557 },
            { fn: "std::panicking::try", file: "/rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs", line: 521 },
            { fn: "std::panic::catch_unwind", file: "/rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panic.rs", line: 350 },
            { fn: "std::thread::Builder::spawn_unchecked_::{{closure}}", file: "/rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/thread/mod.rs", line: 537 },
            { fn: "core::ops::function::FnOnce::call_once{{vtable.shim}}", file: "/rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/ops/function.rs", line: 250 },
            { fn: "<alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once", file: "/rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/alloc/src/boxed.rs", line: 2070 },
            { fn: "<alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once", file: "/rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/alloc/src/boxed.rs", line: 2070 },
            { fn: "std::sys::pal::unix::thread::Thread::new::thread_start", file: "/rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/sys/pal/unix/thread.rs", line: 108 },
            { fn: "start_thread", file: "./nptl/pthread_create.c", line: 447 },
            { fn: "__GI___clone3", file: "./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S", line: 78 },
        ],
    },
)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

It seems that there is no redirect to "new-owner", but I couldn't find where the logic for redirecting is handled... If it's handled in some underlying http crate, then there would be no reason for my code to fail..

**Comment by InAnYan** [comment]
I see now why the tests fail.

The thing I got very confused with is: why it worked in my project...

It worked because I used IDs, but not other things... Now I need to fix this

**Comment by InAnYan** [comment]
@XAMPPRocky tests are fixed

**Comment by XAMPPRocky** [comment]
Thank you for your PR, and congrats on your first contribution! 🎉

**Pull request merged**
