### PR TITLE
Fix the model for parsing responses to a specific commit sha

### PR DESCRIPTION
**Pull request by atilag**
The response from Github API to a request like: 
https://api.github.com/repos/atilag/IBM-Quantum-Systems-Exercise/commits/026880557f1116052c504b5066d1ae90c7c5bcd0
Is something like this:
```json
{
  "sha": "026880557f1116052c504b5066d1ae90c7c5bcd0",
  "node_id": "C_kwDOHOAX6doAKDAyNjg4MDU1N2YxMTE2MDUyYzUwNGI1MDY2ZDFhZTkwYzdjNWJjZDA",
  "commit": {
    "author": {
      "name": "Juan Gomez",
      "email": "atilag@gmail.com",
      "date": "2022-06-20T20:43:02Z"
    },
    "committer": {
     ...
    },
    ...
  "author": {
    "login": "atilag",
    "id": 1304071,
    "node_id": "MDQ6VXNlcjEzMDQwNzE=",
    "avatar_url": "https://avatars.githubusercontent.com/u/1304071?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/atilag",
    "html_url": "https://github.com/atilag",
    "followers_url": "https://api.github.com/users/atilag/followers",
    "following_url": "https://api.github.com/users/atilag/following{/other_user}",
    "gists_url": "https://api.github.com/users/atilag/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/atilag/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/atilag/subscriptions",
    "organizations_url": "https://api.github.com/users/atilag/orgs",
    "repos_url": "https://api.github.com/users/atilag/repos",
    "events_url": "https://api.github.com/users/atilag/events{/privacy}",
    "received_events_url": "https://api.github.com/users/atilag/received_events",
    "type": "User",
    "site_admin": false
  },
  ...
}
```
There are two kinds of "author" keys, but the octocrab model was confusing the one in the root level with the one under the "commit" key. 
I have fixed the models, so the parser doesn't mix them up. 
I have also changed the names to better match the responses' keys.

Nice work team!! It is a pleasure to contribute :)

### CODE REVIEW

**Comment by atilag** [comment]
Yep, let me try fix them.

**Comment by atilag** [comment]
I still need these changes in order to consume the parts of the Github API related to commit information.
I'm for now maintaining my own fork, but I guess eventually someone else would need these changes too.

**Comment by XAMPPRocky** [comment]
Thank you for your PR, and congrats on your first contribution! 🎉 Sorry for the late review, I've been busy with a lot of other projects at the moment.

**Comment by atilag** [comment]
No sorries! Thanks to you for sharing your excellent work :)

**Pull request merged**
