### PR TITLE
Add list_org_memberships_for_authenticated_user

### PR DESCRIPTION
**Pull request by davidmhewitt**
Allows us to get a list of the orgs the current user is a member of, and their role within that org (i.e. "admin", "member", etc)

### CODE REVIEW

**Comment by XAMPPRocky** [comment]
Thank you for your PR! It seems you need to run `cargo fmt`. 🙂

**Comment by davidmhewitt** [comment]
@XAMPPRocky Oops, thanks! Should be good now.

**Comment by XAMPPRocky** [comment]
Thank you for that, would you mind squashing and pushing the commit? I normally wouldn't ask, but it seems something is borked with the workflow run, and it should be fixed by pushing a new commit.

**Comment by XAMPPRocky** [comment]
Thank you for your PR, and congrats on your first contribution! 🎉

**Pull request merged**
