### PR TITLE
OctocrabBuilder::add_header

### PR DESCRIPTION
**Pull request by lpil**
Hello!

This PR enables users to specify headers to be included in every request. This may be useful when using a proxy for GH that requires authentication headers.

Is there a place to write a suitable test for this functionality?

Thanks,
Louis

### CODE REVIEW

**Comment by XAMPPRocky** [comment]
> Is there a place to write a suitable test for this functionality?

LGTM I would just add a test to the bottom of the file.

**Comment by lpil** [comment]
Cool cool. Using wiremock ?

**Comment by XAMPPRocky** [comment]
> Cool cool. Using wiremock ?

Yeah, that would work.

**Comment by lpil** [comment]
Thank you. I've pushed a test

**Comment by XAMPPRocky** [comment]
Thank you for your PR!

**Pull request merged**
