### PR TITLE
feat: Add `create_status` repo endpoint

### PR DESCRIPTION
**Pull request by aspenluxxxy**
I'm sorry I didn't make any good documentation, just can't really do much rn

### CODE REVIEW

**Comment by XAMPPRocky** [comment]
Thank you for your PR! The implementation looks good, however I will need documentation on the public methods before I can accept and merge this. I would recommend just copying the documentation for those methods from `octokit` for the most part. https://octokit.github.io/rest.js/v18#repos-create-commit-status

**Comment by aspenluxxxy** [comment]
Sure, I'll do that later 👍

**Comment by aspenluxxxy** [comment]
Alright, pushed some documentation

**Comment by XAMPPRocky** [comment]
Thank you for your PR, and congrats on your first contribution! 🎉

**Comment by XAMPPRocky** [comment]
This has now been published as 0.8.5

**Pull request merged**
