### PR TITLE
added user's gpg_keys operations for #552

### PR DESCRIPTION
**Pull request by dmgorsky**
/user/gpg_keys
/user/gpg_keys/{gpg_key_id}
#552

### CODE REVIEW

**Comment by dmgorsky** [comment]
idk what to do with
https://docs.github.com/en/rest/users/gpg-keys?apiVersion=2022-11-28#list-gpg-keys-for-a-user
(/users/{username}/gpg_keys)
looks the same as `users("username").gpg_keys().list()`

**Comment by XAMPPRocky** [comment]
I would call it `list_for_user` that accepts a username parameter. It's different because it lets anyone access anyone else's GPG keys.

**Comment by dmgorsky** [comment]
> I would call it `list_for_user` that accepts a username parameter. It's different because it lets anyone access anyone else's GPG keys.

Good, I'll follow this style also for:

/users/{username}/following
/users/{username}/gpg_keys
/users/{username}/followers
/users/{username}/keys
/users/{username}/following/{target_user}
/users/{username}/hovercard
/users/{username}/ssh_signing_keys
/users/{username}/social_accounts

**Comment by dmgorsky** [comment]
> > I would call it `list_for_user` that accepts a username parameter. It's different because it lets anyone access anyone else's GPG keys.
> 
> Good, I'll follow this style also for:
> 
> /users/{username}/following /users/{username}/gpg_keys /users/{username}/followers /users/{username}/keys /users/{username}/following/{target_user} /users/{username}/hovercard /users/{username}/ssh_signing_keys /users/{username}/social_accounts

@XAMPPRocky 
BTW, `users` and `user_by_id` functions (in `lib.rs`) actually create the same `UserHandler`, so perhaps for such 'open data' w/o auth - we could create some top-level builder? 
e.g, instead of 
`users("userid").gpg_keys().list_for_user("another")` 
create 
`anyone().list_gpg_keys_for_user("userid")`, 
`anyone().list_followers_for_user("userid")` 
(or `unauth()` or something)
and so on?

**Comment by dmgorsky** [comment]
> @XAMPPRocky BTW, `users` and `user_by_id` functions (in `lib.rs`) actually create the same `UserHandler`, so perhaps for such 'open data' w/o auth - we could create some top-level builder? e.g, instead of `users("userid").gpg_keys().list_for_user("another")` create `anyone().list_gpg_keys_for_user("userid")`, `anyone().list_followers_for_user("userid")` (or `unauth()` or something) and so on?

I would go with `public()`.

**Comment by XAMPPRocky** [comment]
How does octokit handle this?

**Comment by dmgorsky** [comment]
> How does octokit handle this?
```javascript
        listGpgKeysForAuthenticatedUser: {
            parameters: RequestParameters & Endpoints["GET /user/gpg_keys"]["parameters"];
            response: Endpoints["GET /user/gpg_keys"]["response"];
        };
        listGpgKeysForUser: {
            parameters: RequestParameters & Endpoints["GET /users/{username}/gpg_keys"]["parameters"];
            response: Endpoints["GET /users/{username}/gpg_keys"]["response"];
        };
```
so `ForAuthenticatedUser` or `ForUser`.

**Pull request merged**
