### PR TITLE
Add workflow dispatch functionality

### PR DESCRIPTION
**Pull request by komu**
I cleaned up #151 for merge.

### CODE REVIEW

**Comment by XAMPPRocky** [comment]
Thank you for your PR, and congrats on your first contribution! 🎉

**Comment by CumpsD** [comment]
Awesome, was just looking for this, thanks! Hopefully it's released soon :)

**Comment by CumpsD** [comment]
There's a bug actually:

These 2 are reversed: https://github.com/XAMPPRocky/octocrab/commit/9c27c4769df3478d9c7e710901600204a594e31a#diff-838563966b8446a4490ab7b6abae340f2f1bfc6ed9bca4a366f1db5f2ddf5402R411-R412

```
    pub fn create_workflow_dispatch(
        &self,
        owner: impl Into<String>,
        repo: impl Into<String>,
        workflow_id: impl Into<String>,
        r#ref: impl Into<String>,
    ) -> WorkflowDispatchBuilder<'_> {
        WorkflowDispatchBuilder::new(self.crab,
            repo.into(),
            owner.into(),
            workflow_id.into(),
            r#ref.into()
        )
    }
```

```
pub(crate) fn new(crab: &'octo Octocrab, owner: String, repo: String, workflow_id: String, r#ref: String) -> Self {
```

owner and repo are getting swapped, causing the wrong url to be constructed

**Comment by XAMPPRocky** [comment]
@CumpsD Nice catch, Feel free to open a PR 🙂

**Comment by CumpsD** [comment]
> @CumpsD Nice catch, Feel free to open a PR 🙂

Here you go: https://github.com/XAMPPRocky/octocrab/pull/189

**Comment by XAMPPRocky** [comment]
Both have now been released as part of `0.15.4`

**Pull request merged**
