### PR TITLE
Add delete_ref in RepoHandler

### PR DESCRIPTION
**Pull request by tniessen**
Fixes: https://github.com/XAMPPRocky/octocrab/issues/572

### CODE REVIEW

**Comment by manchicken** [comment]
Tests for these endpoints are pretty straight-forward. [Here's an example: https://github.com/XAMPPRocky/octocrab/blob/main/tests/issues_reactions_delete_test.rs](https://github.com/XAMPPRocky/octocrab/blob/main/tests/issues_reactions_delete_test.rs)

**Comment by tniessen** [comment]
@manchicken Thank you for the reference, I've added a test!

**Review by manchicken — APPROVED** [review]
I can dig it.

**Comment by XAMPPRocky** [comment]
Thank you for your PR!

**Comment by tniessen** [comment]
Thank you @XAMPPRocky!

**Pull request merged**
