### PR TITLE
Add authenticated app request and models

### PR DESCRIPTION
**Pull request by mkroman**
This PR adds a `get()` method to the `AppsRequestHandler` that returns app details for the currently authenticated app.

Example:

```rust
let octocrab = Octocrab::builder().app(…, …).build()?;
let app = octocrab.apps().get().await?;

println!("app name: {}", app.name);
```

Currently marked as draft until #140 gets merged.

### CODE REVIEW

**Comment by mkroman** [comment]
Maybe it's more appropriate if it's in `CurrentAuthHandler`?

**Comment by XAMPPRocky** [comment]
Thank you for your PR! Having it in `current` makes sense to me, as then it could be `octocrab.current().app()`, rather than `octocrab.app().get()`, which I think is clearer.

**Comment by mkroman** [comment]
I moved it to `CurrentAuthHandler` such that it is now `octocrab.current().app()`.

**Comment by XAMPPRocky** [comment]
Thank you for your PR, and congrats on your first contribution! 🎉

**Pull request merged**
