### PR TITLE
Adding support for listing team members.

### PR DESCRIPTION
**Pull request by manchicken**

### CODE REVIEW

**Comment by manchicken** [comment]
Hey @XAMPPRocky, I added `/teams/{slug}/members` support. I've written a test that works, but which I removed since it's not portable (I don't see any way of publicly querying team members; if you know of one I'm happy to add a test back in).

**Comment by XAMPPRocky** [comment]
Thank you for your PR! There are mock tests elsewhere in the codebase that you can use as an example of how to test the method.

**Comment by manchicken** [comment]
> Thank you for your PR! There are mock tests elsewhere in the codebase that you can use as an example of how to test the method.

Hey @XAMPPRocky, thanks! I totally want to add tests, but I don't see the tests for any of the team functionality. I'm still pretty new to Rust, so I might be missing something, but I don't see any tests at all for teams.

I'm happy to try and come up with some if you need, just let me know if there's a place where teams tests are, or if there's another test that you'd like me to use as a model.

Also, if it's alright with you, could you label this "Hacktoberfest"?

**Comment by manchicken** [comment]
Ok, I think I got some tests that will work. Did I borrow another test and re-fit it for the team members endpoint? Yes. Yes I did. It seems to pass, too. Let me know if there are any other tests that you'd like me cover for this endpoint.

**Comment by XAMPPRocky** [comment]
Thank you for your PR, and congrats on your first contribution! 🎉

**Comment by manchicken** [comment]
I'm sorry, could you change the label to "Hacktoberfest-accepted"? I misread the guide. 

Many thanks. Next up, I'm doing pending team invitations. I'll look at the reqwest item next.

**Pull request merged**
