### PR TITLE
Add `list_stargazers` method to `repos` module

### LINKED ISSUE #226: Add StarGazers API Support
Hi there 👋 I was working on a recent [project](https://github.com/lineville/star-scraper) that utilizes the [GitHub StarGazer API](https://docs.github.com/en/rest/activity/starring#about-the-starring-api) and it would be really nice to use this library for it. I'd be happy to contribute a new module called `stars` that would effectively cover the endpoints exposed by the GitHub starring API. Hopefully this would be useful to others as well 🤞 

Is there a contributing guide or can I just fork and create a PR?

### PR DESCRIPTION
**Pull request by lineville**
- Adds a new method called `list_stargazers` on the `repos` module to fetch the `stargazers` of that repo.
- Small formatting changes
- Tests to cover new method

Resolves #226

### CODE REVIEW

**Comment by XAMPPRocky** [comment]
Thank you for your PR, and congratulations on your first contribution! 🎉

**Comment by lineville** [comment]
Awesome, thanks 😄! Do you cut new releases to crates.io manually or on a regular cadence, just curious?

**Comment by XAMPPRocky** [comment]
I cut them manually. I'll make a new release later this week.

**Comment by lineville** [comment]
@XAMPPRocky Any plans to cut a new release sometime soon 😄 ?

**Comment by XAMPPRocky** [comment]
@lineville Yeah, I'll try to cut one this weekend.

**Pull request merged**
